version = 1

[[analyzers]]
name = "javascript"
enabled = true

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "autopep8"
enabled = true

[[transformers]]
name = "standardjs"
enabled = true
